### ISSUE TITLE
any way to include variables in the body of an email?

### ISSUE THREAD

**Issue by idavidson12** [anarchicknight/react-native-communications#19]

**Comment by anarchicknight** [comment]
can you provide an example of what you would like to do?

The body is provided to the email method as a string, it should be easy to compose the string using whatever variables you want before you pass it in to the method.

**Comment by idavidson12** [comment]
I would like to pull variables from the app, including selections made by
the user, and put them into the email that your module helps create. Is
that possible? My attempts at using variables was unsuccessful.

**Comment by anarchicknight** [comment]
This sounds more like a general question regarding how to retrieve values in code through react rather than anything specific to this library. As you need to have the values before you compose the string which you will pass to the email method from this library.

I can take a look to see if I can point you in the right direction though, do you have some sample code which shows how you are trying to obtain the values?
