### ISSUE TITLE
Plans for Android support?

### ISSUE THREAD

**Issue by jforaker** [anarchicknight/react-native-communications#3]
Or know of a phone call component for Android?

**Comment by anarchicknight** [comment]
I would love to at some point - time is very short for me at the moment due to my day job. It's not quite as simple for Android as it was for iOS (due to no LinkingiOS equivalent yet on android side of react-native), but still won't be too difficult - just needs a spare half a day or so for me.

Will leave this open for when I do get around to it - or pull requests are welcome in the meantime.

Not sure if any other alternatives are around - I would suggest going to npmjs.com and doing a search for react-native on there and see what pops up

**Comment by JonnyBGod** [comment]
would this help?

https://github.com/facebook/react-native/commit/ab7b3b2dea21d57717fad68129fb2d1059f405ab

**Comment by anarchicknight** [comment]
thanks for the above - that was indeed just what was needed.

Android support has now been added in release 0.1.0
