### ISSUE TITLE
IOS Support

### ISSUE THREAD

**Issue by CusProjects** [anarchicknight/react-native-communications#48]
Throws a new message when i try to do this
Communications.phonecall(phone, true)

Can't handle url: telprompt:3432343223

**Comment by anarchicknight** [comment]
Are you running on device or emulator?

As far as I know the emulator will not work for some of the methods as it does not have the required system components, the readme does mention this. It is a while since I checked this though.

If you can replicate on actual device let me know otherwise we will close this.

Cheers

**Comment by CusProjects** [comment]
Thanks for the support i'll try on a physical device...

**Comment by anarchicknight** [comment]
closing this as just tested again on an actual device and it is working - emulator does not and will not work as mentioned above
