### ISSUE TITLE
Message modes

### ISSUE THREAD

**Issue by kennetpostigo** [anarchicknight/react-native-communications#60]
Is there different ways to make imessage open? I'm currently porting an app made in objective c to react-native. In the iOS app, when sending a message it opens imessage and once you hit send it returns to your app and your app continues doing whatever it was doing. On the react-native app I hit send and it opens imessage, but after hitting send in imessage it stays in imessage. How do we do this in react-native-communications?

**Comment by anarchicknight** [comment]
How are you doing it in the native app? Are you using one of the provided message composer controllers to initiate sending the message?

All this library does is provide a wrapper on top of the Linking library provided by react native, which as far as I'm aware does not support what you require.

I did release a separate library which may support what you require but I no longer actively maintain it due to time constraints https://github.com/anarchicknight/react-native-message-composer

**Comment by anarchicknight** [comment]
Closing this as feedback provided and nothing more can be done about it via this module
